# Define stages for the pipeline
stages:
  - build
  - test

# Cache dependencies between jobs
cache:
  paths:
    - node_modules/

# Build stage
build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
      - dist/
    expire_in: 1 hour

# Test stage
test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test
  coverage: '/Coverage.*?(\d+(?:\.\d+)?)%/' 